### ISSUE TITLE
Não funciona com Banco do Brasil

### ISSUE THREAD

**Issue by rotasbr** [alexandresanlim/pix-payload-generator.net#1]
Acabei de fazer um teste e não funciona com o banco do brasil.

O App do banco informa que a chave é inválida.

![WhatsApp Image 2020-12-16 at 19 02 32](https://user-images.githubusercontent.com/39776418/102411985-a1c9be00-3fd1-11eb-963c-91a2be067c50.jpeg)

private void button1_Click(object sender, EventArgs e)
{
    var payload = new StaticPayload("minhachave", "teste", new Merchant("meunome", "Rio de Janeiro"));
    var stringToQrCode = payload.GenerateStringToQrCode();

    textBox1.Text = stringToQrCode;

    pictureBox1.Image = CreateQrCode(stringToQrCode);
}

**Comment by alexandresanlim** [comment]
Tenta colar a string gerada neste site: https://pix.nascent.com.br/tools/pix-qr-decoder/
E me informe qual o erro que ele aponta.

**Comment by rotasbr** [comment]
Oi Alexandre. Identifiquei o problema. A chave pix estava incorreta. Pra mim, a chave pix era o "apelido" que a gente cria junto a instituição financeira.  Mas pelo visto é uma chave hexadecimal - que também está associado ao "apelido". Exemplo: c4472b6e-9eaf-4e5c-b0c3-7c5a1a200000.

Corrigido isto, ao ler o QrCode pelo app do banco os dados são identificados corretamente. Muito bom.

Sabe se existe alguma interface publica em que podemos consultar quanto a compensanção de um determinado Pix?

**Comment by alexandresanlim** [comment]
> Oi Alexandre. Identifiquei o problema. A chave pix estava incorreta. Pra mim, a chave pix era o "apelido" que a gente cria junto a instituição financeira. Mas pelo visto é uma chave hexadecimal - que também está associado ao "apelido". Exemplo: c4472b6e-9eaf-4e5c-b0c3-7c5a1a200000.
> 
> Corrigido isto, ao ler o QrCode pelo app do banco os dados são identificados corretamente. Muito bom.

Ótimo que encontrou o problema! Eu estou enviando uma nova versão agora, para melhorar a identificação dos campos.

> Sabe se existe alguma interface publica em que podemos consultar quanto a compensanção de um determinado Pix?
Que eu saiba ainda não existe, mas estou desenvolvendo um neste exato momento, ficara em um pacote separado, mas de qualquer forma deixarei o link deste novo neste repositório.
Lembrando que para consultar uma compensação é preciso que sua chave esteja ligada a um PSP, além disso também é preciso que este PSP gere um ClientId, ClientScret e um certificado para que assim seja possível você acessar as APIs do PIX para fazer a consulta, No meu caso estou usando a Gerencia Net.
