### ISSUE TITLE
Pix não reconhecido

### ISSUE THREAD

**Issue by ivanteles** [alexandresanlim/pix-payload-generator.net#10]
Bom dia, gerei uma chave, na caixa ele passa certinho!
Em todos os outros que teste dá chave inválida!

00020126630014BR.GOV.BCB.PIX0122vendas@endoplus.odo.br0215PEDIDO-ENDOPLUS520400005303986540574.105802BR5928ENDO PLUS COM E SERV LTDA ME6014RIO DE JANEIRO62130509ENDO3446863043A22

**Comment by alexandresanlim** [comment]
Fala Ivan, o Merchant Name (Nome da empresa/vendedor) deve ter no máximo 25 caracteres. Para validar use ferramentas de decode como essa: https://pix.nascent.com.br/tools/pix-qr-decoder/

**Comment by ivanteles** [comment]
Top a ferramenta da validação.
Mas mesmo assim só passou na caixa em qualquer outra instituição falhou.

00020126630014BR.GOV.BCB.PIX0122VENDAS@ENDOPLUS.ODO.BR0215PEDIDO-ENDOPLUS520400005303986540574.105802BR5925ENDO PLUS COM E SERV LTDA6014RIO DE JANEIRO62130509ENDO344686304D455

**Comment by ivanteles** [comment]
mesmo validado na ferramenta com sucesso o código é sempre recusado!

**Comment by ivanteles** [comment]
Eu li o qrcode que esta aqui no GIT e ele tb dá inválido!
