### ISSUE TITLE
ERROR - Invalid CRC

### ISSUE THREAD

**Issue by DiegoSantanadss** [alexandresanlim/pix-payload-generator.net#4]
A string retornada não é válida, não é aceita quando vai ser paga pelo banco. Algumas vezes quando informada no site disponibilizado para validação, o site retorna ERROR - Invalid CRC.

**Comment by alexandresanlim** [comment]
O payload gerou esse QR: 00020126660014br.gov.bcb.pix0136cb0bed1e-d524-40a5-ac5e-2b4122b8711e0204FLIP5204000053039865406120.005802BR5924DIEGO DOS SANTOS SANTANA6008SAOPAULO62090505Teste63046CD6

Colocando no site validador retornou success:
![image](https://user-images.githubusercontent.com/5353685/131217384-54ae856d-65a6-4a0b-b615-e38cf411761f.png)

Escaneando pelo nubank tbem não falhou:
![image](https://user-images.githubusercontent.com/5353685/131217395-e06ee6a9-1994-4b95-ba54-193265a54f85.png)

Sendo assim, não consegui reproduzir seu problema.

**Comment by DiegoSantanadss** [comment]
Fala Alexandre, vou mandar o exemplo completo.

` var cobranca = new Cobranca(_chave: "cb0bed1e-d524-40a5-ac5e-2b4122b8711e")
            {
                SolicitacaoPagador = "FLIP",
                Valor = new Valor
                {
                    Original = "120.00"
                }
            };

            var payload = cobranca.ToPayload("FLIP-CODE-45794794136", new Merchant("DIEGO DOS SANTOS SANTANA", "MURITIBA"));

            var stringToQrCode = payload.GenerateStringToQrCode();`

string gerada ==>> 00020126660014br.gov.bcb.pix0136cb0bed1e-d524-40a5-ac5e-2b4122b8711e0204FLIP5204000053039865406120.005802BR5924DIEGO DOS SANTOS SANTANA6008MURITIBA62250521FLIP-CODE-457947941366304B879

![image](https://user-images.githubusercontent.com/48060338/131236368-95806dd0-a918-4035-8136-74d6cd2c07da.png)


![image](https://user-images.githubusercontent.com/48060338/131236382-4270a829-a593-4452-9955-433fad32e0ac.png)

**Comment by DSBRBrasil** [comment]
Ola,

> Fala Alexandre, vou mandar o exemplo completo.
> 
> `var cobranca = new Cobranca(_chave: "cb0bed1e-d524-40a5-ac5e-2b4122b8711e")
> {
> SolicitacaoPagador = "FLIP",
> Valor = new Valor
> {
> Original = "120.00"
> }
> };
> 
> var payload = cobranca.ToPayload("FLIP-CODE-45794794136", new Merchant("DIEGO DOS SANTOS SANTANA", "MURITIBA"));
> 
> var stringToQrCode = payload.GenerateStringToQrCode();`
> 
> string gerada ==>> 00020126660014br.gov.bcb.pix0136cb0bed1e-d524-40a5-ac5e-2b4122b8711e0204FLIP5204000053039865406120.005802BR5924DIEGO DOS SANTOS SANTANA6008MURITIBA62250521FLIP-CODE-457947941366304B879
> 
> ![image](https://user-images.githubusercontent.com/48060338/131236368-95806dd0-a918-4035-8136-74d6cd2c07da.png)
> 
> ![image](https://user-images.githubusercontent.com/48060338/131236382-4270a829-a593-4452-9955-433fad32e0ac.png)

Ola @DiegoSantanadss , tenta fazer isso:
var payload = cobranca.ToPayload("ID123", new Merchant("DIEGO DOS SANTOS SANTANA", "MURITIBA"));

**Comment by DSBRBrasil** [comment]
@alexandresanlim o mesmo erro ocorreu comigo. vc pode analisar e ver em que posso ajudar ?

**Comment by alexandresanlim** [comment]
> 00020126660014br.gov.bcb.pix0136cb0bed1e-d524-40a5-ac5e-2b4122b8711e0204FLIP5204000053039865406120.005802BR5924DIEGO DOS SANTOS SANTANA6008MURITIBA62250521FLIP-CODE-457947941366304B879

Com esse gerado tbem foi:

![image](https://user-images.githubusercontent.com/5353685/131269715-5bed2b78-68d4-4027-9813-f982108089d2.png)

**Comment by alexandresanlim** [comment]
@DiegoSantanadss  verifique se o problema não é com o banco q vc esta tentando pagar, faça um teste com outros bancos.

**Comment by alexandresanlim** [comment]
> @alexandresanlim o mesmo erro ocorreu comigo. vc pode analisar e ver em que posso ajudar ?

Qria ajudar, mas não estou encontrando o problema, parece q dependendo do banco está com comportamento diferente.

**Comment by DiegoSantanadss** [comment]
@alexandresanlim testei pelo banco Inter e pelo banco Bradesco, ambos os bancos não consigo fazer a leitura para pagamento.

**Comment by alexandresanlim** [comment]
@DiegoSantanadss , eu encontrei essa issue no repo oficial do pix: https://github.com/bacen/pix-api/issues/398

**Comment by andreygsantos** [comment]
@DiegoSantanadss e @alexandresanlim Fiz alguns testes e o erro apareceu. A chave que eu estava usando era o telefone com código de área. Após usar +55 na frente, funcionou perfeitamente. Pode estar ocorrendo algum problema com a chave utilizada.

**Comment by DiegoSantanadss** [comment]
@alexandresanlim dei uma olhada no issue referenciado, mas não acredito que seja o motivo do erro em debate.

Fiz algumas comparações sobre o código QR gerado, por diferentes plataformas. Ao meu entender com os mesmos argumentos passado o resultado deveria ser o mesmo, no entanto, não foi o que ocorreu.

![image](https://user-images.githubusercontent.com/48060338/131422969-c02f5b0a-e098-4539-92ba-83361d0b7897.png)
 
Para os três códigos acima, foram usados os mesmos argumentos. O primeiro utilizando o site [Gerar Pix](https://www.gerarpix.com.br/), o segundo utilizando o aplicativo do banco bradesco(detentora da chave que utilizei) e o último o pacote disponibilizado. Segue o código utlizado abaixo:

`var cobranca = new Cobranca(_chave: "+5575982843072")
            {
                Valor = new Valor
                {
                    Original = "120.00"
                }
            };

            var payload = cobranca.ToPayload("PAGAMENTO123", new Merchant("DIEGO DOS SANTOS SANTANA", "SAOPAULO"));

            var stringToQrCode = payload.GenerateStringToQrCode();`

Argumentos utilizado no site:

![image](https://user-images.githubusercontent.com/48060338/131423078-af470ba1-909d-4649-92ac-ad135d6f04c2.png)

Com isso, podemos concluir que os dois primeiros códigos foram gerados corretamente, já o terceiro(gerado pelo pacote) foge do padrão e apresenta erro quando lido por alguns bancos.

Foi possível notar que "BR.GOV.BCB.PIX" no código gerado pelo pacote vem em letras minúsculas (caixa baixa), e o código CRC não está em conformidade com os dois primeiros. Talvez, alterando o código para gerar  "BR.GOV.BCB.PIX" em caixa alta resolva o problema, pois o código CRC seria gerado conforme essa alteração na string. 

De todo modo, não tenho afinidade com a tecnologia PIX em desenvolvimento, por isso eu mesmo não fiz essa alteração, mas fica minha contribuição.

@andreygsantos o erro que estou recebendo não está sendo devido a chave, fiz os teste também, mas agradeço.

**Comment by alexandresanlim** [comment]
@DiegoSantanadss só com esse comentário com certeza já contribui mto, vou verificar isso q foi analisado por vc, e assim q atualizar o pacote eu aviso aqui. Valeu!

**Comment by DSBRBrasil** [comment]
O fato da caixa alta no BR.GOV.BCB.PIX foi suficiente para alterar o numero CRC, entretanto ao ler a documentacao a caixa baixa é permitida.

**Comment by alexandresanlim** [comment]
> O fato da caixa alta no BR.GOV.BCB.PIX foi suficiente para alterar o numero CRC, entretanto ao ler a documentacao a caixa baixa é permitida.. @alexandresanlim , será que alterando o code do CRC16 funcionaria ?
> [link](https://social.msdn.microsoft.com/Forums/pt-BR/ca33769b-0d8c-4296-b17d-fa14ed32d3a3/como-calcular-o-crc-do-pix?forum=vscsharppt)

Boa! vou tentar isso!

**Comment by alexandresanlim** [comment]
> var payload = cobranca.ToPayload("PAGAMENTO123", new Merchant("DIEGO DOS SANTOS SANTANA", "SAOPAULO"));
> 
>         var stringToQrCode = payload.GenerateStringToQrCode();`

Aparentemente o problema estava na caixa baixa mesmo, mudando para caixa alta e usando o exemplo do @DiegoSantanadss , o Crc16 ficou conforme os outros sistemas q ele colocou de exemplo:

![image](https://user-images.githubusercontent.com/5353685/131513316-6065b02c-11e7-4d57-b3ef-9241ea6f9c39.png)

**Comment by alexandresanlim** [comment]
> O fato da caixa alta no BR.GOV.BCB.PIX foi suficiente para alterar o numero CRC, entretanto ao ler a documentacao a caixa baixa é permitida.. @alexandresanlim , será que alterando o code do CRC16 funcionaria ?
> [link](https://social.msdn.microsoft.com/Forums/pt-BR/ca33769b-0d8c-4296-b17d-fa14ed32d3a3/como-calcular-o-crc-do-pix?forum=vscsharppt)

Não foi preciso alterar o code, aparentemente somente a alteração da caixa alta foi o suficiente.

**Comment by alexandresanlim** [comment]
@DiegoSantanadss  e @DSBRBrasil  correção enviada na versão 1.0.18 do pacote, aguardo o feedback de vcs.

**Comment by DiegoSantanadss** [comment]
@alexandresanlim funcionando perfeitamente! Muito obrigado!

PS: como feedback sugiro colocar no arquivo README.md as limitações de tamanhos e caracteres dos campos, exemplo, o campo "O-TxtId-Aqui" não aceita espaços nem caracteres especiais, somente letras e números.
