### ISSUE TITLE
Descrição do pagamento ausente

### ISSUE THREAD

**Issue by DiegoSantanadss** [alexandresanlim/pix-payload-generator.net#5]
Quando é gerado um pagamento com descrição, a descrição aparece paga o pagador mas não aparece para o recebedor.

Ou seja, quando vou pagar aparece a descrição, mas quando verifico o extrato de pagamentos pix aparece todos os dados, menos a descrição. Ou é uma falha de comunicação entre os bancos ou é um bug.

Banco detentor da chave, Bradesco.

Banco pagador, Inter.

`var cobranca = new Cobranca(_chave: "+5575982843072")
{
SolicitacaoPagador = "FLIP-CODE 12345",
Valor = new Valor
{
Original = "1.00"
}
};

var payload = cobranca.ToPayload("***", new Merchant("DIEGO DOS SANTOS SANTANA", "MURITIBA"));

var stringToQrCode = payload.GenerateStringToQrCode();`

![image](https://user-images.githubusercontent.com/48060338/131663250-efd84f3d-ed39-4b7a-b3ce-cc8cd3ac8b5a.png)

**Comment by alexandresanlim** [comment]
Fala @DiegoSantanadss , temos controle somente de setar a descrição no momento do pagamento, no extrato esse controle é exclusivo do banco.
