### ISSUE TITLE
PIX não reconhecido

### ISSUE THREAD

**Issue by andreygsantos** [alexandresanlim/pix-payload-generator.net#6]
Tenho uma situação onde o PIX é reconhecido para um pagamento e não é reconhecido para outro.  A única diferença entre eles está na string gerada, na descrição do pagamento (2 caracteres a menos), mas a contagem do tamanho está correta. Janela verde gera um PIX reconhecido pelos bancos, enquanto que a janela rosa não funciona. Abaixo estou trazendo os dois exemplos testados. 
![image](https://user-images.githubusercontent.com/82048064/134989464-042f60eb-075b-4771-bdff-412750dc0026.png)

Classe para gerar PIX (OK)
{LibraryPIX.StaticPIX.containerQRCode}
    Description: "REF 08/2021 | MATRIC 200001000025"
    PayLocation: ""
    PayName: "Pedro Henrique Marchini"
    PayValue: "1326,80"
    ReceiveCity: "Guarulhos"
    ReceiveKey: "007a5515-24bf-4afc-8f17-a2b07f7701ec"
    ReceiveName: "Instituto de Ensino Tecnológico Cálculo Zero Ltda"

STRING QRCODE
000201
2695
  0014BR.GOV.BCB.PIX
  0136007a5515-24bf-4afc-8f17-a2b07f7701ec
  0233REF 08/2021 | MATRIC 200001000025
52040000
5303986
54071326.80
5802BR
5924Instituto de Ensino Tecn
6009Guarulhos
62290525SmAYn6Aou4hfzPW34cgU5oTjv
63045A83

QRCODE
000201
2695
  0014BR.GOV.BCB.PIX
  0136007a5515-24bf-4afc-8f17-a2b07f7701ec
  0233REF 08/2021 | MATRIC 200001000025
52040000
5303986
54071326.80
5802BR
5924Instituto de Ensino Tecn
6009Guarulhos
622905256dYPIcOCiIFAp3gD7ZOBTqVtX
630427AC

QRCODE TESTADO 
00020126950014BR.GOV.BCB.PIX0136007a5515-24bf-4afc-8f17-a2b07f7701ec0233REF 08/2021 | MATRIC 20000100002552040000530398654071326.805802BR5924Instituto de Ensino Tecn6009Guarulhos62290525SmAYn6Aou4hfzPW34cgU5oTjv63045A83

Classe para gerar PIX (ERRO)
{LibraryPIX.StaticPIX.containerQRCode}
    Description: "REF 09/2021 | MATRIC 2100050006"
    PayLocation: ""
    PayName: "Ricardo Alves de Souza"
    PayValue: "1000,00"
    ReceiveCity: "Guarulhos"
    ReceiveKey: "007a5515-24bf-4afc-8f17-a2b07f7701ec"
    ReceiveName: "Centro de Educação Infantil Pequeno Príncipe"

STRING QRCODE
000201
2693
  0014BR.GOV.BCB.PIX
  0136007a5515-24bf-4afc-8f17-a2b07f7701ec
  0231REF 09/2021 | MATRIC 2100050006
52040000
5303986
54071000.00
5802BR
5924Centro de Educação Infan
6009Guarulhos
62290525bxVkqRxFH7SivlKho5AgalA4D
63047417

QRCODE
000201
2693
  0014BR.GOV.BCB.PIX
  0136007a5515-24bf-4afc-8f17-a2b07f7701ec
  0231REF 09/2021 | MATRIC 2100050006
52040000
5303986
54071000.00
5802BR
5924Centro de Educação Infan
6009Guarulhos
62290525vx1yy7TKWStfvr4SQVOtxF2h0
6304D7B8

00020126930014BR.GOV.BCB.PIX0136007a5515-24bf-4afc-8f17-a2b07f7701ec0231REF 09/2021 | MATRIC 210005000652040000530398654071000.005802BR5924Centro de Educação Infan6009Guarulhos62290525bxVkqRxFH7SivlKho5AgalA4D63047417

EM TEMPO: Segundo a documentação oficial do BC, o PIX Estático tem TxId com 25 caracteres, diferente do PIX Dinâmico que são 35. Mesmo com as atualizações aplicadas, o problema continua ocorrendo.

1.5.2. Identificador de transação: txid no QR Code estático
O objeto primitivo EMV 62-05 Reference Label, conforme especificado no manual do BR Code, é 
limitado a 25 caracteres e, quando em efeito20, deve ser utilizado para conciliar pagamentos. Trata-se 
de um identificador de transação que deve ser retransmitido intacto pelo PSP do pagador ao gerar a 
ordem de pagamento. Essa informação permitirá ao recebedor identificar e correlacionar a 
transferência, quando recebida, com a apresentação das instruções ao pagador.
Os caracteres permitidos no contexto do Pix para o campo txid (EMV 62-05) são:
• Letras minúsculas, de ‘a’ a ‘z’
• Letras maiúsculas, de ‘A’ a ‘Z’
• Dígitos decimais, de ‘0’ a ‘9’

**Comment by andreygsantos** [comment]
Caracteres especiais não são permitidos. Apesar de não mencionar na documentação oficial, era a única diferença entre os dois exemplos.  Faltou queimar uma pouco mais de neurônios antes de abrir aqui. Valeu.

**Comment by ivanteles** [comment]
Estou com o mesmo problema, na caixa reconhece e nos demais bancos dá aviso de chave inválida!
