### ISSUE TITLE
Erro ao gerar QrCode com chave pelo telefone

### ISSUE THREAD

**Issue by DSBRBrasil** [alexandresanlim/pix-payload-generator.net#7]
Ola Alexandre, tudo bem ?
Acho que temos um problema com a geração de qrcode com a chave por telefone.
segue as strings para comparação, a chave é : +55(71) 99607-4734

ERRADO (Gerado pela biblioteca):
00020126360014BR.GOV.BCB.PIX0114+5571996074734520400005303986540510.005802BR5910SUPER_BIKE6008SALVADOR62120508PAGID771630456FB

CERTO:
00020126360014BR.GOV.BCB.PIX0114+557199607473452040000530398654041.005802BR5904nome6006cidade62130509pagamento63045537

Tem alguma ideia para que nós possamos resolver ?
Parabens! sua biblioteca é show !

**Comment by DSBRBrasil** [comment]
Olá Alexandre,
Informo que o code funciona muito bem com telefone, só informo para os próximos que o problema estava na geração da imagem pelo googleApis, em alguns casos (a chave por telefone) não funciona
https://chart.googleapis.com/chart?chs=400x400&cht=qr&chl=  (cole aqui a string pix)
Problema resolvido usando a biblioteca 👍 https://github.com/codebude/QRCoder/     para gerar uma imagem base64

**Comment by alexandresanlim** [comment]
Boa! obrigado pela sugestão.
