### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by marcelomera** [alexandresanlim/pix-payload-generator.net#8]
Alexandre, desculpa a minha ignorancia, estou entrando agora no assunto e eu não entendi o "O-TxtId-Aqui" do código abaixo:

var payload = cobranca.ToPayload("O-TxtId-Aqui", new Merchant("Alexandre Sanlim", "Presidente Prudente"));

Eu gostaria de gerar apenas o QrCode Static com o valor definido e com o numero do Pedido, apenas para facilitar a impressão do pedido sem nenhum integração de API com o Banco, e até questionar se esse seu projeto irá servir. 

Obrigado por compartilha seu código.

**Comment by alexandresanlim** [comment]
Opa Marcelo, blz? O Txid é o id de identificação da transação, ele pode ser definido por vc mesmo.

**Comment by marcelomera** [comment]
Obrigado Alexandre, parabéns pelo código.

**Comment by ivanmonteiro** [comment]
> Opa Marcelo, blz? O Txid é o id de identificação da transação, ele pode ser definido por vc mesmo.

Tem como recuperar o Txid quando receber o pagamento?

**Comment by alexandresanlim** [comment]
Opa @ivanmonteiro , na cobrança estática vc não consegue recuperar qualquer tipo de informação, ela é só uma "ponte" para cobrança Pix, a não ser que vc faça esse tipo de controle pelo extrato do próprio banco. Para recuperar informação vc precisaria criar a cobrança dinâmica.

Sobre a Mensagem, vc consegue colocar qualquer informação, basta preencher a propriedade "SolicitacaoPagador".

**Comment by ivanmonteiro** [comment]
> Opa @ivanmonteiro , na cobrança estática vc não consegue recuperar qualquer tipo de informação, ela é só uma "ponte" para cobrança Pix, a não ser que vc faça esse tipo de controle pelo extrato do próprio banco. Para recuperar informação vc precisaria criar a cobrança dinâmica.
> 
> Sobre a Mensagem, vc consegue colocar qualquer informação, basta preencher a propriedade "SolicitacaoPagador".

Estou utilizando o pix estático mesmo e consigo recuperar o id de transação no aplicativo do banco e tem atendido ao que eu queria no momento. Uma solução simples e sem custo para mim. Não é automatizado mas atende meus requisitos no momento!

**Comment by DSBRBrasil** [comment]
> > Opa @ivanmonteiro , na cobrança estática vc não consegue recuperar qualquer tipo de informação, ela é só uma "ponte" para cobrança Pix, a não ser que vc faça esse tipo de controle pelo extrato do próprio banco. Para recuperar informação vc precisaria criar a cobrança dinâmica.
> > Sobre a Mensagem, vc consegue colocar qualquer informação, basta preencher a propriedade "SolicitacaoPagador".
> 
> Funcionou, estou utilizando o pix estático mesmo e consigo recuperar o id de transação no aplicativo do banco e tem atendido ao que eu queria no momento. Uma solução simples e sem custo para mim. Não é automatizado mas atende meus requisitos no momento!

Poderia usar webhook para obter informacoes sobre pagamento. Estou pesquisando sobre...
