### ISSUE TITLE
Dúvida sobre formato da chave

### ISSUE THREAD

**Issue by felipe-weblite** [alexandresanlim/pix-payload-generator.net#9]
Olá, tenho uma dúvida no `new Cobranca("cahve_pix");`. Sabemos que são diversos tipos de chave, desde CPF até chave aleatória. Para que o QR Code seja válido, é preciso inserir a chave com máscara ou sem? Ex: CPF "123.456.789-00" ou "12345678900"

**Comment by alexandresanlim** [comment]
Sem máscara.

**Comment by felipe-weblite** [comment]
> Opa, blz Felipe? Sem máscara.

Máscara só no tipo de chave aleatória, certo? Que é o GUID. As demais, tudo sem máscara. É isso?
